### ISSUE TITLE
algorithmically compute roots

### ISSUE THREAD

**Issue by scottkellum** [at-import/Sassy-math#1]
Use an algorithm to compute roots instead of feedback loops. It will be more verbose but less processor intensive and faster.

http://en.wikipedia.org/wiki/Methods_of_computing_square_roots

**Comment by Snugug** [comment]
Rewrite nth-root based on nth-root algorithm:
Inspiration:
http://en.wikipedia.org/wiki/Nth_root_algorithm

**Comment by Snugug** [comment]
SassScript solves this issue! w00t!
