### ISSUE TITLE
Trig functions

### ISSUE THREAD

**Issue by scottkellum** [at-import/Sassy-math#2]
Still trying to find a complete formula, a lot of the ones I am coming across are simplified or use circular logic. Combining simplified versions should point us in the right direction.

http://en.wikipedia.org/wiki/Trigonometric_function

**Comment by scottkellum** [comment]
http://www.homeschoolmath.net/teaching/sine_calculator.php via @Snugug

**Comment by sultancillo** [comment]
pushed first very rough implementation of sine, assumes angle in radians. Maybe designers like this to be on degrees rather?

**Comment by Snugug** [comment]
http://en.wikipedia.org/wiki/Trigonometric_functions#Series_definitions

I noticed that the current Sine function doesn't calculate pi/2=1, so I think some more work needs to be done on it. I'm looking at cosine now

**Comment by sultancillo** [comment]
fixed... the function now normalizes angles outside than pi/2 and -pi/2

**Comment by Snugug** [comment]
Uh oh, did you pull before doing that? I abstracted out the Taylor series to be used with both Cosine and Sine and had that fixed…
Maybe we should work off of branches so we don't have these kinds of issues?

**Comment by sultancillo** [comment]
weird… i pulled before but i did not get those changes...

## 

Mario Valencia
Mobile: +52-81-1588-4556
Follow me on Twitter: @sultancillo
LinkedIn: http://www.linkedin.com/in/mariovalencia

**Comment by Snugug** [comment]
I see the issue, I had committed but forgot to push.
I've merged the two files together, using the new updated fix for the Taylor series. We should be good now.
