### ISSUE TITLE
Should exponent() be able to accept a fraction?

### ISSUE THREAD

**Issue by gavinmcfarland** [at-import/Sassy-math#25]
Hi, in your readme file you mention being able to us

``` sass
exponent($base, $power_numerator, $power_denominator)
```

However this function only accepts two arguments. Have I misunderstand the meaning here?

**Comment by Snugug** [comment]
You cannot put fractions in directly, but that's what the numerator and denominator are for. You can see the function [here](https://github.com/Team-Sass/Sassy-math/blob/master/compass/lib/sassy-math.rb#L7). There is also the [power](https://github.com/Team-Sass/Sassy-math/blob/master/compass/lib/sassy-math.rb#L14) function that only takes an exponent.

In fractions, the top number is called a numerator and the bottom number is called the denominator. If, say, you wanted to do 2^1/2, you would pass in `exponent(2, 1, 2)`.

**Comment by gavinmcfarland** [comment]
Ah ok, I see. It's just I saw the sass mixin defined here and it looked like it only accepted two arguments.

``` sass
@function exponent($base, $exponent) {
  // reset value
  $value: $base;
  // positive intergers get multiplied
  @if $exponent > 1 {
    @for $i from 2 through $exponent {
      $value: $value * $base; } }
  // negitive intergers get divided. A number divided by itself is 1
  @if $exponent < 1 {
    @for $i from 0 through -$exponent {
      $value: $value / $base; } }
  // return the last value written
  @return $value; 
}
```

Thanks
