### ISSUE TITLE
Sassy-math does not accept Compass Version >= 1.0.0 as a valid version of Compass to satisfy its dependency requirements

### ISSUE THREAD

**Issue by lozandier** [at-import/Sassy-math#26]
At least on windows,  sass-math fails `bundler update` `bundle install`  commands on   Rails 4.0.1+ if the version of Compass is ver `1.0` or higher...
![screenshot 4073](https://f.cloud.github.com/assets/1223224/1686069/f63c05e0-5de0-11e3-99b4-28db3274e906.png)

**Comment by Snugug** [comment]
Will be fixed in the next update.

**Comment by yuvilio** [comment]
Made pull request to address. This. In the meantime a local monkey patch of `compass/sassy-math.gemspec` and a gem build and gem install from the compass/ directory (see the comment in the pull request) seems to have fixed it for now.
