### ISSUE TITLE
Convert to SCSS

### ISSUE THREAD

**Issue by Snugug** [at-import/Sassy-math#3]
Would anyone be opposed to me converting this to SCSS? For me, with lots of nested if/else and for loops, SCSS is a lot easier to keep track of everything.

**Comment by scottkellum** [comment]
You can use sass-convert to set up a parallel file. The CORDIC method might be a lot cleaner in SCSS.

feel free to close this once you are satisfied, don't worry about syntax yet. This isn't public for a reason.
