### ISSUE TITLE
Remove Compass as a dependency?

### ISSUE THREAD

**Issue by joshdcomp** [at-import/Sassy-math#30]
Compass is a huge dependency on a project…is there any way to make Sassy-math independent?

**Comment by scottkellum** [comment]
Sassy-math is written in Ruby, not Sass. While it could work with Ruby Sass, the process would be more complex than adding Compass and installing this plugin.

As a result, Compass is the only install path we officially support.

**Comment by joshdcomp** [comment]
For posterity, I did find a non-compass sass math lib: https://github.com/terkel/mathsass
