### ISSUE TITLE
Move to Branch/Pull Request Model

### ISSUE THREAD

**Issue by Snugug** [at-import/Sassy-math#5]
What are people's thoughts on moving from a "push straight to master" model to a "branch and issue pull request" model? This would help with us stepping on each other's toes and make it easier to keep track of discrete pieces to be worked on.
Thoughts?

**Comment by Snugug** [comment]
I've started doing my work ing a branch/pull request model. If there is n opposition, can we as a group move to this, if for no other reason than to have more than one set of eyes on what's getting pushed in?
Anyway, ln I've done some work on! w00t!

**Comment by scottkellum** [comment]
done then? lets close it now that we are doing that.
