### ISSUE TITLE
move to an ego-free organization

### ISSUE THREAD

**Issue by scottkellum** [at-import/Sassy-math#6]
Thinking about creating an organization for stuff like this so we all can take more equal ownership. Either that or move to @thesassway.

**Comment by adamstac** [comment]
Fine by me if that's what you'd like to do. So these projects would be community projects?

**Comment by scottkellum** [comment]
They are for the community and heavily developed by more than just me. I plan on making it public and licensing it the same as modular-scale.

Private for now, but yes, eventually for the community.

**Comment by Snugug** [comment]
FWIW, I'm cool with this.

**Comment by adamstac** [comment]
The bad part is that for org's to have private repo's it costs $$, same for users too.

**Comment by scottkellum** [comment]
Just needs to be when public. Everyone here cool with my name being on here until this goes public? We can move the project over then.

**Comment by codingdesigner** [comment]
makes sense to me. part of being ego-free is not worrying about whose account we work on, right?
